# Generated by Django 5.2 on 2025-08-08 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espacios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_uso', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('motivo', models.TextField(verbose_name='Motivo de reserva')),
                ('motivo_admin', models.TextField(blank=True, default='', null=True, verbose_name='Mensaje de aprobación/rechazo')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='espacios.espacio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_uso', 'hora_inicio'],
                'indexes': [models.Index(fields=['espacio', 'fecha_uso'], name='reservas_re_espacio_552dbd_idx'), models.Index(fields=['fecha_uso'], name='reservas_re_fecha_u_8c08ea_idx')],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'espacio', 'fecha_uso'), name='uniq_usuario_espacio_fecha', violation_error_message='Ya existe una reserva para este usuario en este espacio el mismo día.'), models.CheckConstraint(condition=models.Q(('hora_inicio__lt', models.F('hora_fin'))), name='check_hora_inicio_menor_fin', violation_error_message='La hora de inicio debe ser menor a la hora de fin.')],
            },
        ),
    ]
