# Generated by Django 5.2 on 2025-08-29 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequerimientoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('produccion', 'Producción'), ('comunicacional', 'Comunicacional'), ('otro', 'Otro')], max_length=100)),
            ],
            options={
                'verbose_name': 'Requerimiento de Reserva',
                'verbose_name_plural': 'Requerimientos de Reservas',
                'ordering': ['-reserva__fecha_uso', 'reserva__hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_uso', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('motivo', models.TextField(verbose_name='Motivo de reserva')),
                ('motivo_admin', models.TextField(blank=True, default='', null=True, verbose_name='Mensaje de aprobación/rechazo')),
                ('numero_participantes', models.IntegerField(default=1, verbose_name='Número de participantes')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_cambio_estado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cambio de estado')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_uso', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DetalleReservaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anfitrion_usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('espacio_transmision', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion_transmision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_digitales', to='core.ubicacion')),
            ],
            options={
                'verbose_name': 'Detalle Reserva Digital',
                'verbose_name_plural': 'Detalles de Reservas Digitales',
                'ordering': ['-reserva__fecha_uso', 'reserva__hora_inicio'],
            },
        ),
    ]
