# Generated by Django 5.2 on 2025-09-19 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espacios', '0002_initial'),
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserva',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='espacios.espacio'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['espacio', 'fecha_uso'], name='reservas_re_espacio_552dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_uso'], name='reservas_re_fecha_u_8c08ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('usuario', 'espacio', 'fecha_uso'), name='uniq_usuario_espacio_fecha', violation_error_message='Ya existe una reserva para este usuario en este espacio el mismo día.'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('hora_inicio__lt', models.F('hora_fin'))), name='check_hora_inicio_menor_fin', violation_error_message='La hora de inicio debe ser menor a la hora de fin.'),
        ),
    ]
