# Generated by Django 5.2 on 2025-09-15 19:03

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0001_initial'),
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('hora_inicio__gte', datetime.time(8, 0)), ('hora_fin__lte', datetime.time(22, 0))), name='check_hora_inicio_menor_fin_8am_10pm', violation_error_message='Solo se permite reservar entre las 8:00 AM y las 10:00 PM.'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_uso__gte', datetime.date(2025, 9, 15))), name='check_fecha_uso_futuro_o_hoy', violation_error_message='La fecha de uso debe ser hoy o en el futuro.'),
        ),
    ]
