"""
Django settings for my_app project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from cProfile import label
from pathlib import Path
import os
import ldap
from django.urls import reverse_lazy
from django_auth_ldap.config import LDAPSearch, GroupOfNamesType
import environ

# Inicializa django-environ
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
# Toma variables desde el archivo .env
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])


# Application definition

INSTALLED_APPS = [
    'fontawesomefree',
    'auditlog',
    'django_filters',
    'widget_tweaks',
    'compressor',
    'django.contrib.humanize',

    'apps.reservas',
    'apps.usuarios',
    'apps.espacios',
    'apps.reportes',
    'apps.logs',
    'apps.core',

    'formtools',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]


COMPRESS_ROOT = BASE_DIR / 'static'

STATIC_URL = "static/"
STATICFILES_FINDERS = [
    # para tus archivos en STATICFILES_DIRS
    'django.contrib.staticfiles.finders.FileSystemFinder',
    # para los static/ de cada app (incluye admin)
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # compresión y concatenación de CSS/JS
    'compressor.finders.CompressorFinder',
]


USE_I18N = True

LANGUAGE_CODE = "es-es"         # o "es" (ambos funcionan)
LANGUAGES = [
    ("es", "Español"),
    ("en", "English"),
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "auditlog.middleware.AuditlogMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'DIRS': [BASE_DIR / 'templates'],
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'library.context_proccesors.dashboard_access.dashboard_access',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT', default='5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


USE_L10N = True
USE_TZ = True


TIME_ZONE = 'America/Caracas'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Parametros agregados/modificados
COMPRESS_ENABLED = True
STATIC_ROOT = BASE_DIR / 'static'
AUTH_USER_MODEL = 'usuarios.Usuario'
APPEND_SLASH = True 
LOGIN_REDIRECT_URL = '/inicio/'
LOGIN_URL = '/'
LOGOUT_REDIRECT_URL = '/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# LDAP Config

AUTH_LDAP_SERVER_URI = env("LDAP_SERVER_URI")
AUTH_LDAP_BIND_DN = env("LDAP_BIND_DN")
AUTH_LDAP_BIND_PASSWORD = env("LDAP_BIND_PASSWORD")

AUTH_LDAP_USER_SEARCH = LDAPSearch(
    env("LDAP_BASE_DN"),
    ldap.SCOPE_SUBTREE,
    env("LDAP_USER_FILTER"),
)

AUTH_LDAP_CONNECTION_OPTIONS = {
        ldap.OPT_DEBUG_LEVEL: 0,
        ldap.OPT_REFERRALS: 0,
}

AUTH_LDAP_ALWAYS_UPDATE_USER = True
AUTH_LDAP_CACHE_GROUPS = True
AUTH_LDAP_GROUP_CACHE_TIMEOUT = 3600

AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "email": "mail", 
    "username": "sAMAccountName",
    "last_name": "sn",
    "telefono": "telephoneNumber",
    "p00":"employeeid", }

AUTH_LDAP_GROUP_BASE = "ou=Siscolvir,ou=Grupos,dc=cantv,dc=com, dc=ve"
AUTH_LDAP_GROUP_FILTER = "(objectClass=group)"
AUTH_LDAP_GROUP_SEARCH = LDAPSearch(AUTH_LDAP_GROUP_BASE,
                                   ldap.SCOPE_SUBTREE, AUTH_LDAP_GROUP_FILTER)

AUTH_LDAP_GROUP_TYPE = GroupOfNamesType(name_attr="cn")
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    'is_staff': 'cn=NACMOVI,' + AUTH_LDAP_GROUP_BASE,
    'is_support': 'cn=NACMOVI,' + AUTH_LDAP_GROUP_BASE,
    'is_superuser': 'cn=NACMOVI,' + AUTH_LDAP_GROUP_BASE,
}

AUTHENTICATION_BACKENDS = (
'django.contrib.auth.backends.ModelBackend',
)

class GRUPOS:
    ADMINISTRADOR = 'administrador'
    MODERADOR = 'moderador'
    USUARIO = 'usuario'

class MODELOS  :
    LOGENTRY = {'label':'Actividad', 'name':'auditlog.LogEntry', 'url':'log'}
    USUARIO = {'label':'Usuarios', 'name':'usuarios.Usuario', 'url':'usuarios'}
    ESPACIO = {'label':'Espacios', 'name':'espacios.Espacio', 'url':'espacios'}
    RESERVA = {'label':'Reservas', 'name':'reservas.Reserva', 'url':'reserva'}
    dict = {
        'LogEntry': LOGENTRY,
        'Usuario': USUARIO,
        'Espacio': ESPACIO,
        'Reserva': RESERVA,
    }
    

DASHBOARD_ACCESS = {
    GRUPOS.ADMINISTRADOR: 
        [
            {'model': MODELOS.RESERVA, 'perms':['add', 'change', 'view', 'delete']},
            {'model': MODELOS.USUARIO, 'perms':['add', 'change', 'view', 'delete']},
            {'model': MODELOS.ESPACIO, 'perms':['add', 'change', 'view', 'delete']},
            {'model': MODELOS.LOGENTRY, 'perms':['view']},

        ],
    GRUPOS.MODERADOR: 
         [
            {'model': MODELOS.RESERVA, 'perms':['add', 'change', 'view', 'delete']},
            {'model': MODELOS.USUARIO, 'perms':['add', 'change', 'view', 'delete']},
            {'model': MODELOS.LOGENTRY, 'perms':['view']},

         ],
    GRUPOS.USUARIO:   
        [
            {'model': MODELOS.RESERVA, 'perms':['add', 'change', 'view', 'delete']},
            {'model': MODELOS.LOGENTRY, 'perms':['view']},

        ],
}