"""
Django settings for my_app project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from cProfile import label
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_889w=q*7^50mv#48&eigo9t*b82t*k_uk@8cneb324bod&(+9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'fontawesomefree',
    "crispy_forms",
    "crispy_tailwind",
    'auditlog',
    'django_filters',
    'widget_tweaks',
    'compressor',
    'django.contrib.humanize',

    'reservas',
    'apps.usuarios',
    'apps.espacios',
    'apps.logs',


    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"

CRISPY_TEMPLATE_PACK = "tailwind"
COMPRESS_ROOT = BASE_DIR / 'static'

STATIC_URL = "static/"
STATICFILES_FINDERS = [
    # para tus archivos en STATICFILES_DIRS
    'django.contrib.staticfiles.finders.FileSystemFinder',
    # para los static/ de cada app (incluye admin)
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # compresión y concatenación de CSS/JS
    'compressor.finders.CompressorFinder',
]


USE_I18N = True

LANGUAGE_CODE = "es-es"         # o "es" (ambos funcionan)
LANGUAGES = [
    ("es", "Español"),
    ("en", "English"),
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "auditlog.middleware.AuditlogMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'DIRS': [BASE_DIR / 'templates'],
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'reservas.library.context_proccesors.dashboard_access.dashboard_access',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


USE_L10N = True
USE_TZ = True


TIME_ZONE = 'America/Caracas'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Parametros agregados/modificados
COMPRESS_ENABLED = True
STATIC_ROOT = BASE_DIR / 'static'
AUTH_USER_MODEL = 'usuarios.Usuario'
APPEND_SLASH = True 
LOGIN_REDIRECT_URL = '/inicio/'
LOGIN_URL = '/'
LOGOUT_REDIRECT_URL = '/'


class GRUPOS:
    ADMINISTRADOR = 'administrador'
    MODERADOR = 'moderador'
    USUARIO = 'usuario'

class MODELOS  :
    LOGENTRY = {'label':'Actividad', 'name':'auditlog.LogEntry', 'url':'log'}
    USUARIO = {'label':'Usuarios', 'name':'usuarios.Usuario', 'url':'usuarios'}
    ESPACIO = {'label':'Espacios', 'name':'espacios.Espacio', 'url':'espacios'}
    RESERVA = {'label':'Reservas', 'name':'reservas.Reserva', 'url':'reserva'}
    dict = {
        'LogEntry': LOGENTRY,
        'Usuario': USUARIO,
        'Espacio': ESPACIO,
        'Reserva': RESERVA,
    }
    

DASHBOARD_ACCESS = {
    GRUPOS.ADMINISTRADOR: 
        [
            {'model': MODELOS.RESERVA, 'perms':['add', 'change', 'view', 'delete']},
            {'model': MODELOS.USUARIO, 'perms':['add', 'change', 'view', 'delete']},
            {'model': MODELOS.ESPACIO, 'perms':['add', 'change', 'view', 'delete']},
            {'model': MODELOS.LOGENTRY, 'perms':['view']},

        ],
    GRUPOS.MODERADOR: 
         [
            {'model': MODELOS.RESERVA, 'perms':['add', 'change', 'view', 'delete']},
            {'model': MODELOS.USUARIO, 'perms':['add', 'change', 'view', 'delete']},
            {'model': MODELOS.LOGENTRY, 'perms':['view']},

         ],
    GRUPOS.USUARIO:   
        [
            {'model': MODELOS.RESERVA, 'perms':['add', 'change', 'view', 'delete']},
            {'model': MODELOS.LOGENTRY, 'perms':['view']},

        ],
}
