# Generated by Django 5.2 on 2025-08-26 19:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_alter_usuario_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlataformaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Plataforma Digital',
                'verbose_name_plural': 'Plataformas Digitales',
            },
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z0-9 ]*', message='El nombre del espacio debe comenzar con una letra, y solo puede contener letras, números y espacios.')])),
                ('capacidad_maxima', models.PositiveSmallIntegerField(help_text='Capacidad máxima (≤ 5000)', validators=[django.core.validators.MaxValueValidator(5000), django.core.validators.MinValueValidator(1)])),
                ('tipo', models.CharField(choices=[('fisico', 'Físico'), ('digital', 'Digital')], max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Espacio',
                'verbose_name_plural': 'Espacios',
                'ordering': ['tipo', 'nombre'],
                'indexes': [models.Index(fields=['tipo'], name='espacios_es_tipo_48984b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacidad_maxima__lte', 5000)), name='check_capacidad_max_5000'), models.CheckConstraint(condition=models.Q(('tipo__in', ['fisico', 'digital'])), name='check_tipo_valido', violation_error_message="El tipo de espacio debe ser 'fisico' o 'digital'.")],
            },
        ),
        migrations.CreateModel(
            name='DetalleEspacioFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.PositiveSmallIntegerField(help_text='Piso en que se encuentra el espacio (≤ 40)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('tipo', models.CharField(choices=[('salon', 'Salón'), ('laboratorio', 'Laboratorio'), ('auditorio', 'Auditorio')], max_length=20)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios_fisicos', to='usuarios.ubicacion')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_fisicos', to='espacios.espacio')),
            ],
            options={
                'verbose_name': 'Detalle Espacio Físico',
                'verbose_name_plural': 'Detalles de Espacios Físicos',
                'constraints': [models.UniqueConstraint(fields=('espacio',), name='uniq_espacio_fisico', violation_error_message='Ya existe un detalle de espacio físico para este espacio.')],
            },
        ),
        migrations.CreateModel(
            name='DetalleEspacioDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_digitales', to='espacios.espacio')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='espacios.plataformadigital')),
            ],
            options={
                'verbose_name': 'Detalle Espacio Digital',
                'verbose_name_plural': 'Detalles de Espacios Digitales',
                'constraints': [models.UniqueConstraint(fields=('espacio',), name='uniq_espacio_digital', violation_error_message='Ya existe un detalle de espacio digital para este espacio.')],
            },
        ),
    ]
