# Generated by Django 5.2 on 2025-08-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='espacio',
            name='check_tipo_valido',
        ),
        migrations.AddField(
            model_name='espacio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
