# Generated by Django 5.2 on 2025-09-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleespaciofisico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='espacios/fisicos/'),
        ),
        migrations.AlterField(
            model_name='detalleespaciofisico',
            name='tipo',
            field=models.CharField(choices=[('salon', 'Salón'), ('laboratorio', 'Laboratorio'), ('auditorio', 'Auditorio'), ('otro', 'Otro')], max_length=20),
        ),
    ]
