# Generated by Django 5.2 on 2025-08-28 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espacios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='espacio',
            name='check_tipo_valido',
        ),
        migrations.AddField(
            model_name='espacio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='detalleespaciofisico',
            name='espacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacio', to='espacios.espacio'),
        ),
    ]
