# Generated by Django 5.2 on 2025-09-19 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espacios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.ubicacion'),
        ),
        migrations.AddIndex(
            model_name='espacio',
            index=models.Index(fields=['ubicacion', 'piso'], name='espacios_es_ubicaci_d62e06_idx'),
        ),
        migrations.AddConstraint(
            model_name='espacio',
            constraint=models.CheckConstraint(condition=models.Q(('capacidad__lte', 1000)), name='check_capacidad_max_1000'),
        ),
    ]
