# Generated by Django 5.2 on 2025-09-04 13:55

import apps.espacios.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('espacios', '0002_detalleespaciofisico_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleespaciodigital',
            name='url',
            field=models.URLField(blank=True, help_text='URL del espacio digital', null=True),
        ),
        migrations.AlterField(
            model_name='detalleespaciodigital',
            name='plataforma',
            field=models.ForeignKey(help_text='Plataforma del espacio digital', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.plataformadigital'),
        ),
        migrations.AlterField(
            model_name='detalleespaciofisico',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=apps.espacios.models.user_directory_path),
        ),
    ]
