# Generated by Django 5.2 on 2025-08-25 23:05

import apps.usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(error_messages={'unique': 'Ya existe un Usuario con este nombre.'}, help_text='Nombre de usuario único. 3-20 caracteres. Debe comenzar con letra.', max_length=20, unique=True, validators=[apps.usuarios.models.validate_username], verbose_name='Nombre de usuario'),
        ),
    ]
