# Generated by Django 5.2 on 2025-09-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='p00',
            field=models.CharField(help_text='Código P00 único del usuario (8 caracteres).', max_length=9, unique=True, verbose_name='P00'),
        ),
    ]
