# Generated by Django 5.2 on 2025-09-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_p00'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='gerencia',
            field=models.CharField(blank=True, help_text='Gerencia del usuario', max_length=40, verbose_name='Gerencia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='vicepresidencia',
            field=models.CharField(blank=True, help_text='Vicepresidencia del usuario', max_length=40, verbose_name='Vicepresidencia'),
        ),
    ]
