# Generated by Django 5.2 on 2025-05-23 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='capacidad',
            field=models.PositiveSmallIntegerField(help_text='Capacidad máxima (≤ 1000)', validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='espacio',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='espacio',
            name='piso',
            field=models.PositiveSmallIntegerField(help_text='Piso en que se encuentra el espacio (≤ 40)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='nombre',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
