# Generated by Django 5.2 on 2025-05-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='capacidad',
            field=models.PositiveIntegerField(max_length=10000),
        ),
    ]
