# Generated by Django 5.2 on 2025-05-27 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_espacio_capacidad_alter_espacio_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacio',
            name='nombre',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z0-9_ ]*[a-zA-Z0-9]$', message='El nombre del espacio debe comenzar y terminar con una letra o número, y solo puede contener letras, números, guiones bajos y espacios.')]),
        ),
    ]
