# Generated by Django 5.2 on 2025-06-03 18:39

import django.core.validators
import reservas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_espacio_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='motivo_admin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='espacio',
            name='nombre',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z0-9 ]*', message='El nombre del espacio debe comenzar con una letra o número, y solo puede contener letras, números y espacios.')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con este nombre.'}, help_text='Nombre de usuario único. 3-20 caracteres. Debe comenzar con letra.', max_length=20, unique=True, validators=[reservas.models.validate_username], verbose_name='Nombre de usuario'),
        ),
        migrations.AlterConstraint(
            model_name='reserva',
            name='uniq_usuario_espacio_fecha',
            constraint=models.UniqueConstraint(fields=('usuario', 'espacio', 'fecha_uso'), name='uniq_usuario_espacio_fecha', violation_error_message='Ya existe una reserva para este usuario en este espacio el mismo día.'),
        ),
        migrations.AlterConstraint(
            model_name='reserva',
            name='check_hora_inicio_menor_fin',
            constraint=models.CheckConstraint(condition=models.Q(('hora_inicio__lt', models.F('hora_fin'))), name='check_hora_inicio_menor_fin', violation_error_message='La hora de inicio debe ser menor a la hora de fin.'),
        ),
    ]
