# Generated by Django 5.2 on 2025-06-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reserva_motivo_admin_alter_espacio_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='motivo',
            field=models.TextField(verbose_name='Motivo de reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='motivo_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de gestión'),
        ),
    ]
