# Generated by Django 5.2 on 2025-06-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_alter_reserva_motivo_alter_reserva_motivo_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='motivo_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de aprobación/rechazo'),
        ),
    ]
