# Generated by Django 5.2 on 2025-06-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_alter_reserva_motivo_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
