# Generated by Django 5.2 on 2025-06-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_reserva_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='espacio',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
