# Generated by Django 5.2 on 2025-06-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_remove_reserva_descripcion_espacio_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacio',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
