# Generated by Django 5.2 on 2025-06-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_espacio_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='motivo_admin',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Mensaje de aprobación/rechazo'),
        ),
    ]
