# Generated by Django 5.2 on 2025-06-17 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_alter_reserva_motivo_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['username'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='espacio',
            name='capacidad',
            field=models.PositiveSmallIntegerField(help_text='Capacidad máxima (≤ 1000)', validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_uso'], name='reservas_re_fecha_u_8c08ea_idx'),
        ),
    ]
